### ISSUE TITLE
got error on import

### ISSUE THREAD

**Issue by yggdrasildy** [kensiprell/bootstrap-framework-sample#2]
seems this line in build.gradle: classpath "com.bertramlabs.plugins:asset-pipeline-gradle:$assetPiplineGradleVersion"

should read: classpath "com.bertramlabs.plugins:asset-pipeline-gradle:$assetPipelineGradleVersion"

**Comment by kensiprell** [comment]
Thanks, I'll get this fixed. Obviously, I was improperly using [search and replace](https://github.com/kensiprell/bootstrap-framework-sample/issues/1).

Ken
